# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 21:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_point_id', models.IntegerField(db_index=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('estimation_method', models.CharField(choices=[('Counted', 'Counted'), ('Estimated', 'Estimated')], db_index=True, max_length=9)),
                ('estimation_method_detail', models.TextField()),
                ('road', models.TextField(db_index=True)),
                ('road_category', models.CharField(choices=[('PM', 'M or Class A Principal Motorway'), ('PR', 'Class A Principal road in Rural area'), ('PU', 'Class A Principal road in Urban area'), ('TM', 'M or Class A Trunk Motorway'), ('TR', 'Class A Trunk road in Rural area'), ('TU', 'Class A Trunk road in Urban area'), ('BR', 'Class B road in Rural area'), ('BU', 'Class B road in Urban area'), ('CR', 'Class C road in Rural area'), ('CU', 'Class C road in Urban area'), ('UR', 'Class U road in Rural area'), ('UU', 'Class U road in Urban area ')], max_length=2)),
                ('start_junction', models.TextField(blank=True)),
                ('end_junction', models.TextField(blank=True)),
                ('link_length_km', models.FloatField()),
                ('link_length_miles', models.FloatField()),
                ('pedal_cycles', models.PositiveIntegerField()),
                ('motorcycles', models.PositiveIntegerField()),
                ('cars_taxis', models.PositiveIntegerField()),
                ('buses_coaches', models.PositiveIntegerField()),
                ('light_goods_vehicles', models.PositiveIntegerField()),
                ('two_axle_rigid_hgv', models.PositiveIntegerField()),
                ('three_axle_rigid_hgv', models.PositiveIntegerField()),
                ('four_or_five_axle_rigid_hgv', models.PositiveIntegerField()),
                ('three_or_four_axle_articulated_hgv', models.PositiveIntegerField()),
                ('five_axle_articulated_hgv', models.PositiveIntegerField()),
                ('six_or_more_axle_articulated_hgv', models.PositiveIntegerField()),
                ('all_hgvs', models.PositiveIntegerField()),
                ('all_motor_vehicles', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
