# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='count',
            options={'ordering': ['year', 'count_point_id']},
        ),
    ]
